[package]
name = "p2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "p2"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
