[package]
name = "p1"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "p1"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minicbor = { version = "0.18.0", features = ["alloc", "derive"] }
